name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests and Generate Report
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests with pytest and generate HTML report
      run: |
        pytest -vv --html=report.html --self-contained-html tests/
    
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
        retention-days: 30

  deploy:
    name: Upload Code Artifact
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Upload code artifact
      uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: |
          src/
          tests/
          requirements.txt
        retention-days: 30
